name: "Liam's Cool GitHub Actions Workflow"

on: 
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code from repository
        uses: actions/checkout@v4

      - name: Build application
        run: echo "Building the app..."

      - name: Run tests
        run: |
          echo "Testing the app..."
          echo "All the tests passed!"

      - name: Deploy app
        run: | 
          echo "Deploying the app..."
          ls
